# Generated by Django 4.2.20 on 2025-04-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grievance_social_protection", "0018_alter_comment_user_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalticket",
            name="account_detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="account_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="beneficiary_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="cni_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="code_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="colline",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="commune",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="exclusion_detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="exclusion_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="form_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="gps_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="is_anonymous",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="is_batwa",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="is_beneficiary",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="is_project_related",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="is_resolved",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="non_beneficiary_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="other_beneficiary_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="other_channel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="payment_detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="payment_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="phone_detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="phone_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="province",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="receiver_function",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="receiver_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="receiver_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="reporter_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="reporter_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="resolution_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="resolver_function",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="resolver_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="vbg_detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="vbg_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="viol_complaint",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="viol_hospital",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="viol_support",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="zone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="account_detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="account_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="beneficiary_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="cni_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="code_date",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="colline",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="commune",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="exclusion_detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="exclusion_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="form_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="gps_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="is_anonymous",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="is_batwa",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="is_beneficiary",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="is_project_related",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="is_resolved",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="non_beneficiary_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="other_beneficiary_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="other_channel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="payment_detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="payment_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="phone_detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="phone_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="province",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="receiver_function",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="receiver_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="receiver_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="reporter_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="reporter_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="resolution_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="resolver_function",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="resolver_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="vbg_detail",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="vbg_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="viol_complaint",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="viol_hospital",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="viol_support",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="zone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
